default: &default
  adapter: mysql2
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>
  encoding: utf8
  collation: utf8_unicode_ci

development:
  <<: *default
  database: chatbot_development

test:
  <<: *default
  database: chatbot_test

production:
  <<: *default
  database: chatbot_production
